### PR TITLE
use Bootstrap, improve interface

### PR DESCRIPTION
**Pull request by jancborchardt**
This is the beginning of the interface overhaul. Initially it might partly look like Bootstrap, but that will change.

This pull request is so that the code bases don’t diverge (also because I’m done for the day). I’ll continue to work mostly on the index.html and styles.css from now on.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Btw, No idea why there are so many merge commits in there. Gitflow seems to introduce hell of a lot of branches where pure git would be way easier.

**Comment by brolund** [comment]
Ah, I thought I removed jQuery UI, but I missed the css files. :-)

I changed the default branch of the repo to develop. Right now, develop===master, but features should be branched from develop.

I thought that about gitflow at first, but now I love it. :-)  It is fairly simple. 

master 
is what is in prod. To get it there you create a (usually short-lived) release branch with 
git flow release start/finish <name>
The release branch is created from what is in develop.
New features are created from develop with
git flow feature start <name>
it just creates a branch under features/<name>. 
git flow feature finish 
merges that feature branch back to develop.

I guess you can do what you like locally. I'll pull your branches by name. The important thing is to start from develop, not master. :-)

**Comment by johlrogge** [comment]
Actually, once the release-branches have been finished there is no need to keep them in git-hub so they can be pushed with git push :release/0.7.0 for instance.

I don't see why there is a need to merge anything but develop. Gitflow is not really magic and it keeps a clean history.

My suggestion for the future: make develop default (if it isn't allready) branch from develop and merge to develop (ignore other merges even if github generates them)

**Comment by brolund** [comment]
Hehehe, cool!!! I like what you did!!! :-D 

All the tests are not running for me, but I think those are minor issues from the new look. I just need to find the elements.

Also, when using a more narrow browser window, the logotype disappears. This might be a feature, but I think it should be there on a 800px width. Can you have bootstrap replace the logotype with a smaller one for the narrow screen instead of just hiding it?

**Comment by brolund** [comment]
Ah, I think the logo disappearing is from having the logo as a navigation item.

**Comment by jancborchardt** [comment]
Yeah, I know about branching from develop, as I did with my other fixes. These merges occured because I added this repo as remote and accidentally pulled master into develop without noticing.

Anyway, I fixed the logo and navigation items getting hidden. It’s still pretty rough, but everything except for the status page works on mobile now. Would be cool if you can pull it in, I’ll work on the status page next.

**Comment by brolund** [comment]
Excellent! :-)
Pulled your stuff into develop. I had to make some minor fixes to make the tests pass (like ids and some changed matches in the tests), and I reinstated the footer that got lost at some point. :-)

**Comment by jancborchardt** [comment]
Thanks!
I actually removed the footer knowingly and put the Info in the about page. I thought about putting all the Github and donation info in the footer, but that would make the whole thing too crowded. Not every page needs to say that the stuff is freely licensed. :)

**Comment by brolund** [comment]
It is not totally freely licensed, it is CC Share Alike. :-) From what I have understood about the bizarre laws of copyright, we need to announce the copyright on all our web pages. I think the same goes for licensing. Hence the footer. :-P

We also want to have the donation buttons in the header since the donations is the the only source of income we'll have from this. If that makes the header a few pixels higher, that is ok with us. :-)

**Comment by brolund** [comment]
Oh, crap. http://wiki.creativecommons.org/FFAQ#Can_I_apply_a_Creative_Commons_license_to_software.3F

**Comment by jancborchardt** [comment]
@brolund yeah, the software should probably be AGPL v3 (and later). Regarding donation links, I will put all the license and donation info in the footer which will appear on every page then. (Later, I’m at a conference atm.)

**Pull request merged**
