### PR TITLE
pink

### PR DESCRIPTION
**Pull request by froderik**
Can change color to pink - still "not blue" upon load though.... Not sure if the tiny piece of script is added to the correct place in the require.js world. At least it works!

### CODE REVIEW

**Comment by brolund** [comment]
Hahaha, nice one! We'll think about it for a bit, pros and cons. :-)

Maybe we can use the code for something I wanted to do for a long time: I'd like to have a site change color and light depending on season and time of day... Hmmm...

**Comment by jancborchardt** [comment]
Haha! Yeah, tough call.

I’d say we don’t have a color picker, especially because there’s no »blue« stuff in there anymore. @froderik if you still see the old design, hard reload with Ctrl+Shift+R.

**Comment by froderik** [comment]
It was just for fun! We talked about pink at agical yesterday and it wasn't that hard to put in there. The "not blue" option refers to brolunds argumentation for picking orange.

But this is a hack and it could be done more properly. I would suggest developing a couple of themes to switch between. An the place to switch maybe could be on a future page for user settings.

**Comment by brolund** [comment]
:-) I'll close this with a won't fix. ;-)

**Pull request closed without merging**
